USE CircusDW;

DROP TABLE IF EXISTS AttendingTheShow;
DROP TABLE IF EXISTS PerformanceEvaluation;
DROP TABLE IF EXISTS TicketAcquiring;
DROP TABLE IF EXISTS TakingPart;
DROP TABLE IF EXISTS IsIn;
DROP TABLE IF EXISTS Date;
DROP TABLE IF EXISTS Places;
DROP TABLE IF EXISTS Times;
DROP TABLE IF EXISTS Seating;
DROP TABLE IF EXISTS TicketType;
DROP TABLE IF EXISTS Animals;
DROP TABLE IF EXISTS Performers;
DROP TABLE IF EXISTS Performance;
